version: "3"

services:
    # image project
    app:
        container_name: especializati-laravel-dash
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-9

    # nginx
    nginx:
        container_name: especializati-nginx-dash
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-9

    # redis
    redis:
        container_name: especializati-redis-dash
        image: redis:latest
        networks:
            - laravel-9

networks:
    laravel-9:
        driver: bridge
